### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by timflutre** [Gregor-Mendel-Institute/mlmm#1]
Hello,
it would be easier to have an [R package](http://r-pkgs.had.co.nz/) rather than scripts. I could find some time to package your scripts (or part of them) into a package, via pull requests to your repo.
But for that I first need to know the licence. More specifically, I would like to know if you agree to licence it under the GPL-3+.
Best,
Tim

**Comment by timeu** [comment]
Hi @timflutre thank you for offering to package the scripts. We definately would appreciate it. 
I think GPL-3+ should be fine but let me ask the original authors, if they are ok with it.

**Comment by timflutre** [comment]
great, thanks

**Comment by timeu** [comment]
@timflutre I talked to @bvilhjal and he is fine with the license. If you do a pull request, I can merge it. 
Thanks!

**Comment by timflutre** [comment]
great, thanks, I'll start by doing a pull request to add the license, and then try to find some time to quickly refactor the current code into an R package

**Comment by timflutre** [comment]
thanks for the merge!
