### ISSUE TITLE
unused arguments

### ISSUE THREAD

**Issue by draperry** [Gregor-Mendel-Institute/mlmm#10]
I have tried running through mlmm using Vincent Segura's pdf tutorial (2013) and keep coming up with the  following error:
 
Error in mlmm(Y = pheno$Phenot1, X = geno_imp, K = K_mat, nbchunks = 2,  : 
  unused arguments (Y = pheno$Phenot1, X = geno_imp, K = K_mat, nbchunks = 2, maxsteps = 10)

This happens if I use my own data or the example data. Any ideas?!

Thanks, Annika

**Comment by visegura** [comment]
Dear Annika,
It seems that another package called "mlmm" has recently been released on CRAN (https://cran.r-project.org/package=mlmm). So this might be the reason of your problem. Could you please check which mlmm is currently installed on your system ? If it is the one from CRAN just remove it and install the one from github using the following commands:
library(devtools); install_github("Gregor-Mendel-Institute/mlmm")
Hope this helps,
Vincent

**Comment by draperry** [comment]
Thank you very much for the fast reply, it is much appreciated. I have done as you suggested and it now works!

Best wishes, Annika
