### ISSUE TITLE
Error in installing mlmm

### ISSUE THREAD

**Issue by visegura** [Gregor-Mendel-Institute/mlmm#6]
I just tried to install the package from github and got the following error:
Error : package ‘emma’ 0.1.0 trouvé, mais >= 1.1.2 est nécessaire pour ‘mlmm’
ERROR: lazy loading failed for package ‘mlmm’
(R 3.2.2 on linux)
The problem is that the emma package on CRAN does not correspond to the efficient mixed model association. It stands for Evolutionary model-based multiresponse approach. So this package is not a dependency of mlmm, in place the emma.r function should be provided.

**Comment by timflutre** [comment]
It's indeed not the emma pkg on CRAN but the emma pkg at UCLA, [here](http://mouse.cs.ucla.edu/emma/). Maybe @timeu could mention this in the README?

**Comment by timeu** [comment]
@timflutre Should I just mention to install the emma package manually in the installation section of the README ? Maybe you could do a quick pull request ?

**Comment by timflutre** [comment]
done
